-- Enable UUID extension just in case (usually enabled by default)
create extension if not exists "uuid-ossp";

-- Table: media
-- Stores metadata about the movies and series to avoid redundant TMDB calls for list usage
create table public.media (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  tmdb_id bigint not null,
  media_type text not null check (media_type in ('movie', 'tv')),
  title text not null,
  poster_url text,
  unique(tmdb_id, media_type)
);

-- Enable RLS on media
alter table public.media enable row level security;

-- Policy: Media is public readable (or at least readable by authenticated users)
create policy "Media is viewable by everyone" on public.media
  for select using (true);
  
-- Policy: Allow authenticated users to insert media (if your app logic creates media entries on the fly)
create policy "Authenticated users can insert media" on public.media
  for insert with check (auth.role() = 'authenticated');


-- Table: user_library
-- Stores the user's relationship with the media (progress, rating, watchlist, etc.)
create table public.user_library (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  media_id bigint references public.media(id) not null,
  status text not null check (status in ('watching', 'awaiting_episodes', 'watchlist', 'watched')),
  
  -- Series Tracking
  last_episode_seen int default 0,
  total_episodes int default 0,
  
  -- Timestamps
  last_watched_at timestamp with time zone,
  watched_at timestamp with time zone, -- When it was finished/rated
  
  -- Rating & Review
  rating int check (rating >= 0 and rating <= 5),
  review_text text,

  -- Ensure a user only has one entry per media item
  unique(user_id, media_id)
);

-- Enable RLS on user_library
alter table public.user_library enable row level security;

-- Policies for user_library
create policy "Users can view their own library" on public.user_library
  for select using (auth.uid() = user_id);

create policy "Users can insert into their own library" on public.user_library
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own library" on public.user_library
  for update using (auth.uid() = user_id);

create policy "Users can delete from their own library" on public.user_library
  for delete using (auth.uid() = user_id);
